// AUTO-GENERATED by packages/contracts/scripts/gen_typescript.py
// DO NOT EDIT BY HAND. Run: uv run --package contracts python packages/contracts/scripts/gen_typescript.py

export type TicketCategory = "hardware" | "software" | "network" | "access" | "security" | "other";

export type PIILevel = "routine" | "sensitive" | "critical" | "mask_failed";

export type Branch = "auto_reply" | "auto_route" | "hitl" | "block" | "escalate";

export type ReviewQueue = "pii_verify" | "low_confidence" | "injection" | "mask_failed" | "runbook_approval";

export type ReviewAction = "approve" | "edit_and_send" | "reject" | "reroute" | "escalate";

export type Verdict = "correct" | "wrong" | "partial" | "not_applicable";

export type UserRole = "employee" | "technician" | "manager" | "security";

export type RiskTier = "low" | "medium" | "high";

export type ReasonCode = "injection_detected" | "pii_critical" | "pii_mask_failed" | "schema_invalid" | "mass_incident" | "retrieval_below_floor" | "kb_not_authorized" | "quote_invalid" | "quote_source_not_in_topk" | "negation_mismatch" | "trust_below_auto_threshold" | "trust_below_route_threshold" | "category_inconsistent" | "ai_engine_unavailable" | "budget_exceeded" | "circuit_open" | "all_checks_passed";

export interface TicketIn {
  subject: string;
  body: string;
  attachments?: string[];
}

export interface TicketMasked {
  ticket_public_id: string;
  subject_masked: string;
  body_masked: string;
  pii_level: PIILevel;
  placeholder_keys?: string[];
}

export interface AutoReplyProposal {
  proposed_intent: "auto_reply";
  kb_slug: string;
  verbatim_quote: string;
  answer_draft: string;
  self_confidence: number;
}

export interface RouteProposal {
  proposed_intent: "route_to_team";
  proposed_category: TicketCategory;
  proposed_subcategory?: string | null;
  rationale: string;
  self_confidence: number;
}

export interface RunbookProposal {
  proposed_intent: "runbook";
  runbook_id: string;
  draft_payload: Record<string, unknown>;
  proposed_category: TicketCategory;
  self_confidence: number;
}

export interface InsufficientContext {
  proposed_intent: "insufficient_context";
  missing_information: string;
}

export interface RetrievalSignals {
  rerank_top1: number;
  rerank_margin: number;
  bm25_keyword_hit: boolean;
  docs_above_floor: number;
  topk_chunk_ids?: number[];
}

export interface GenerationSignals {
  schema_valid: boolean;
  quote_match_ratio: number;
  quote_source_in_topk: boolean;
  negation_consistent: boolean;
  category_consistent: boolean;
  quote_applicable?: boolean;
}

export interface PolicySignals {
  kb_auto_reply_allowed: boolean;
  kb_risk_tier: string;
  pii_level: PIILevel;
  injection_detected: boolean;
  mass_incident: boolean;
}

export interface TrustSignals {
  retrieval: RetrievalSignals;
  generation: GenerationSignals;
  policy: PolicySignals;
  llm_self_confidence?: number | null;
}

export interface TrustScore {
  value: number;
  model_version: string;
  contributions?: Record<string, unknown>;
}

export interface KBArticleMeta {
  id: number;
  slug: string;
  category: TicketCategory;
  auto_reply_allowed: boolean;
  risk_tier: RiskTier;
}

export interface RoutingDecision {
  branch: Branch;
  reason_code: ReasonCode;
  reason_detail?: string;
  gate_failed?: string | null;
  trust?: number | null;
  category?: TicketCategory | null;
  kb_slug?: string | null;
  queue?: ReviewQueue | null;
  priority?: number;
  draft_payload?: Record<string, unknown> | null;
  alert_security?: boolean;
}

export interface AIRunRequest {
  request_id: string;
  ticket: TicketMasked;
  retrieval_floor: number;
  max_tokens: number;
  max_llm_calls: number;
  max_latency_sec: number;
  max_graph_iterations: number;
  prompt_version?: string;
}

export interface AIRunResponse {
  request_id: string;
  graph_version: string;
  prompt_version: string;
  model: string;
  proposal: LLMProposalEnvelope | null;
  signals: TrustSignals;
  retrieved_chunks?: Record<string, unknown>[];
  tokens_in?: number;
  tokens_out?: number;
  cost_usd?: number;
  latency_ms?: number;
  degraded_reason?: string | null;
}

export type LLMProposal =
  | AutoReplyProposal
  | RouteProposal
  | RunbookProposal
  | InsufficientContext;

export type LLMProposalEnvelope = LLMProposal;
