# Generated by Django 6.0.7 on 2026-07-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("review", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunbookExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("runbook_id", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("result", models.JSONField(default=dict)),
                ("status", models.CharField(default="succeeded", max_length=20)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runbook_executions",
                        to="review.reviewitem",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runbook_executions",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "runbook_executions",
            },
        ),
    ]
