#!/usr/bin/env python3
"""
Generate `services/web/lib/types/generated.ts` from the Pydantic contracts.

Usage:
    uv run --package contracts python packages/contracts/scripts/gen_typescript.py

This is the only legitimate way `generated.ts` changes. Nothing in
`services/web` should hand-edit that file — see spec §2 rule 1.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

MODELS = [
    "TicketIn",
    "TicketMasked",
    "AutoReplyProposal",
    "RouteProposal",
    "RunbookProposal",
    "InsufficientContext",
    "RetrievalSignals",
    "GenerationSignals",
    "PolicySignals",
    "TrustSignals",
    "TrustScore",
    "KBArticleMeta",
    "RoutingDecision",
    "AIRunRequest",
    "AIRunResponse",
]

ENUMS = {
    "TicketCategory": ["hardware", "software", "network", "access", "security", "other"],
    "PIILevel": ["routine", "sensitive", "critical", "mask_failed"],
    "Branch": ["auto_reply", "auto_route", "hitl", "block", "escalate"],
    "ReviewQueue": [
        "pii_verify",
        "low_confidence",
        "injection",
        "mask_failed",
        "runbook_approval",
    ],
    "ReviewAction": ["approve", "edit_and_send", "reject", "reroute", "escalate"],
    "Verdict": ["correct", "wrong", "partial", "not_applicable"],
    "UserRole": ["employee", "technician", "manager", "security"],
    "RiskTier": ["low", "medium", "high"],
}

REASON_CODES = [
    "injection_detected",
    "pii_critical",
    "pii_mask_failed",
    "schema_invalid",
    "mass_incident",
    "retrieval_below_floor",
    "kb_not_authorized",
    "quote_invalid",
    "quote_source_not_in_topk",
    "negation_mismatch",
    "trust_below_auto_threshold",
    "trust_below_route_threshold",
    "category_inconsistent",
    "ai_engine_unavailable",
    "budget_exceeded",
    "circuit_open",
    "all_checks_passed",
]


def emit_enum(name: str, values: list[str]) -> str:
    members = " | ".join(f'"{v}"' for v in values)
    return f"export type {name} = {members};\n"


def emit_json_schema(model_name: str) -> str:
    """Pull the Pydantic JSON schema and render a minimal TS interface.

    Kept deliberately simple (no external json-schema-to-ts dependency) —
    this repo's contracts are flat enough that a small hand-rolled mapper
    is more maintainable than a heavy codegen dependency.
    """
    import contracts as c

    model = getattr(c, model_name)
    schema = model.model_json_schema()
    return _schema_to_ts(model_name, schema)


PY_TO_TS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "object": "Record<string, unknown>",
}


def _ts_type(prop: dict, defs: dict) -> str:
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    if "anyOf" in prop:
        parts = [_ts_type(p, defs) for p in prop["anyOf"] if p.get("type") != "null"]
        parts = parts or ["unknown"]
        out = " | ".join(dict.fromkeys(parts))
        if any(p.get("type") == "null" for p in prop["anyOf"]):
            out += " | null"
        return out
    if prop.get("type") == "array":
        return f"{_ts_type(prop.get('items', {}), defs)}[]"
    if "enum" in prop:
        return " | ".join(f'"{v}"' for v in prop["enum"])
    if "const" in prop:
        return f'"{prop["const"]}"'
    return PY_TO_TS.get(prop.get("type"), "unknown")


def _schema_to_ts(name: str, schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, prop in props.items():
        opt = "" if field in required else "?"
        lines.append(f"  {field}{opt}: {_ts_type(prop, schema.get('$defs', {}))};")
    lines.append("}\n")
    return "\n".join(lines)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[3]
    out_path = repo_root / "services/web/lib/types/generated.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    chunks = [
        "// AUTO-GENERATED by packages/contracts/scripts/gen_typescript.py",
        "// DO NOT EDIT BY HAND. Run: uv run --package contracts python "
        "packages/contracts/scripts/gen_typescript.py",
        "",
    ]

    for name, values in ENUMS.items():
        chunks.append(emit_enum(name, values))

    chunks.append(emit_enum("ReasonCode", REASON_CODES))

    for model_name in MODELS:
        chunks.append(emit_json_schema(model_name))

    # The discriminated union itself (contracts.llm_draft.LLMProposal /
    # LLMProposalEnvelope) isn't one of MODELS above — model_json_schema()
    # on the RootModel wrapper doesn't flatten into a plain interface the
    # way the four concrete variants do. Emit it directly instead of
    # letting AIRunResponse.proposal reference an undefined type.
    chunks.append(
        "export type LLMProposal =\n"
        "  | AutoReplyProposal\n"
        "  | RouteProposal\n"
        "  | RunbookProposal\n"
        "  | InsufficientContext;\n\n"
        "export type LLMProposalEnvelope = LLMProposal;\n"
    )

    out_path.write_text("\n".join(chunks))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    main()
