# Generated by Django 6.0.7 on 2026-07-27 15:27

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # CREATE EXTENSION vector must run before this migration's
        # VectorField columns (TicketEmbedding.embedding).
        ("dbextras", "0001_extensions_and_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("prompt_version", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("graph_version", models.CharField(max_length=50)),
                ("proposed_draft", models.JSONField(blank=True, null=True)),
                (
                    "llm_self_confidence",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("trust_signals", models.JSONField()),
                (
                    "trust_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("retrieved_chunks", models.JSONField(default=list)),
                ("tokens_in", models.IntegerField(blank=True, null=True)),
                ("tokens_out", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("degraded_reason", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_runs",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hardware", "hardware"),
                            ("software", "software"),
                            ("network", "network"),
                            ("access", "access"),
                            ("security", "security"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(max_length=20)),
                ("detected_by", models.CharField(max_length=30)),
                ("ticket_count", models.IntegerField(default=0)),
                ("detection_window_min", models.IntegerField(blank=True, null=True)),
                (
                    "baseline_rate",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("status", models.CharField(default="open", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "incidents",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.CharField(max_length=32, unique=True)),
                ("subject_masked", models.TextField()),
                ("body_masked", models.TextField()),
                (
                    "pii_level",
                    models.CharField(
                        choices=[
                            ("routine", "routine"),
                            ("sensitive", "sensitive"),
                            ("critical", "critical"),
                            ("mask_failed", "mask_failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pii_map", models.JSONField(default=dict)),
                ("status", models.CharField(default="new", max_length=20)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hardware", "hardware"),
                            ("software", "software"),
                            ("network", "network"),
                            ("access", "access"),
                            ("security", "security"),
                            ("other", "other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("assigned_team", models.CharField(blank=True, max_length=50, null=True)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_count", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="tickets.incident",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
            },
        ),
        migrations.CreateModel(
            name="PiiAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ref", models.UUIDField()),
                ("reason", models.TextField()),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "pii_access_log",
            },
        ),
        migrations.CreateModel(
            name="TicketEmbedding",
            fields=[
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding_row",
                        serialize=False,
                        to="tickets.ticket",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ticket_embeddings",
            },
        ),
        migrations.CreateModel(
            name="RoutingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("branch", models.CharField(max_length=20)),
                ("reason_code", models.CharField(max_length=50)),
                ("reason_detail", models.TextField()),
                ("gate_failed", models.CharField(blank=True, max_length=100, null=True)),
                ("thresholds_used", models.JSONField()),
                ("shadow_mode", models.BooleanField(default=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_decisions",
                        to="tickets.airun",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_decisions",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "routing_decisions",
            },
        ),
        migrations.CreateModel(
            name="PiiQuarantine",
            fields=[
                ("ref", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("ciphertext", models.BinaryField()),
                ("nonce", models.BinaryField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarantine_entries",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "pii_quarantine",
            },
        ),
        migrations.AddField(
            model_name="airun",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_runs",
                to="tickets.ticket",
            ),
        ),
    ]
