# Generated by Django 6.0.7 on 2026-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="held_decision",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="source",
            field=models.CharField(
                choices=[("form", "form"), ("chat", "chat")], default="form", max_length=10
            ),
        ),
    ]
