# Generated by Django 6.0.7 on 2026-09-29 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_id", models.UUIDField(blank=True, null=True)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("event", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_log",
            },
        ),
    ]
