# Generated by Django 6.0.7 on 2026-10-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewitem",
            name="queue",
            field=models.CharField(
                choices=[
                    ("pii_verify", "pii_verify"),
                    ("low_confidence", "low_confidence"),
                    ("injection", "injection"),
                    ("mask_failed", "mask_failed"),
                    ("runbook_approval", "runbook_approval"),
                    ("clarification", "clarification"),
                ],
                max_length=30,
            ),
        ),
    ]
