# Generated by Django 6.0.7 on 2026-09-29 00:53

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FewshotExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hardware", "hardware"),
                            ("software", "software"),
                            ("network", "network"),
                            ("access", "access"),
                            ("security", "security"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_json", models.JSONField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
                ),
                ("approved_at", models.DateTimeField()),
                ("user_confirmed", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("retracted_at", models.DateTimeField(blank=True, null=True)),
                ("retract_reason", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fewshot_examples",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "fewshot_examples",
            },
        ),
    ]
