"""
Smart Ticket Triage — shared contracts.

This package is the single source of truth for every schema shared between
`core-api` and `ai-engine` (see architecture-spec-v2 §2, rule 1). Nothing in
either Python service should redefine these types; Next.js consumes a
TypeScript projection generated by `scripts/gen_typescript.py`.

Naming convention: every field authored by the LLM carries a `proposed_`
(or `self_`) prefix. This is a deliberate type-level reminder that the
value is a *suggestion*, not a decision — see ADR-0001 and ADR-0003.
"""

from contracts.enums import Branch, PIILevel, ReasonCode, TicketCategory
from contracts.ticket import TicketIn, TicketMasked
from contracts.llm_draft import (
    AutoReplyProposal,
    InsufficientContext,
    LLMProposal,
    LLMProposalEnvelope,
    RouteProposal,
    RunbookProposal,
)
from contracts.trust import (
    GenerationSignals,
    PolicySignals,
    RetrievalSignals,
    TrustScore,
    TrustSignals,
)
from contracts.routing import KBArticleMeta, RoutingDecision, Thresholds
from contracts.ai_request import AIRunRequest, AIRunResponse

__all__ = [
    "Branch",
    "PIILevel",
    "ReasonCode",
    "TicketCategory",
    "TicketIn",
    "TicketMasked",
    "AutoReplyProposal",
    "InsufficientContext",
    "LLMProposal",
    "LLMProposalEnvelope",
    "RouteProposal",
    "RunbookProposal",
    "GenerationSignals",
    "PolicySignals",
    "RetrievalSignals",
    "TrustScore",
    "TrustSignals",
    "KBArticleMeta",
    "RoutingDecision",
    "Thresholds",
    "AIRunRequest",
    "AIRunResponse",
]
