"""
core-api's schema contracts.

Each service is deployed on its own, so each holds its own copy of the
schemas it needs instead of importing a shared package (ADR-0010). This is
the full set: core-api owns every decision, so `Branch`, `ReasonCode`,
`RoutingDecision`, `Thresholds` and `TrustScore` exist only here. ai-engine
keeps a trimmed copy of the wire types in `ai_engine/contracts/`.

The core-api ↔ ai-engine wire (`AIRunRequest`, `AIRunResponse` and every
type they contain) is defined in BOTH copies. Change it in both in the same
PR — `evals/suites/test_contract_parity.py` fails on any drift. Next.js
consumes a TypeScript projection of this copy, generated by
`scripts/gen_typescript.py`.

Naming convention: every field authored by the LLM carries a `proposed_`
(or `self_`) prefix. This is a deliberate type-level reminder that the
value is a *suggestion*, not a decision — see ADR-0001 and ADR-0003.
"""

from contracts.enums import Branch, PIILevel, ReasonCode, TicketCategory
from contracts.ticket import TicketIn, TicketMasked
from contracts.llm_draft import (
    AutoReplyProposal,
    InsufficientContext,
    LLMProposal,
    LLMProposalEnvelope,
    RouteProposal,
    RunbookProposal,
)
from contracts.trust import (
    GenerationSignals,
    PolicySignals,
    RetrievalSignals,
    TrustScore,
    TrustSignals,
)
from contracts.routing import KBArticleMeta, RoutingDecision, Thresholds
from contracts.ai_request import AIRunRequest, AIRunResponse

__all__ = [
    "Branch",
    "PIILevel",
    "ReasonCode",
    "TicketCategory",
    "TicketIn",
    "TicketMasked",
    "AutoReplyProposal",
    "InsufficientContext",
    "LLMProposal",
    "LLMProposalEnvelope",
    "RouteProposal",
    "RunbookProposal",
    "GenerationSignals",
    "PolicySignals",
    "RetrievalSignals",
    "TrustScore",
    "TrustSignals",
    "KBArticleMeta",
    "RoutingDecision",
    "Thresholds",
    "AIRunRequest",
    "AIRunResponse",
]
