# Generated by Django 6.0.7 on 2026-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kbarticle",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="kbarticle",
            name="slug",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
