# Generated by Django 6.0.7 on 2026-09-29 15:09

from django.db import migrations


class Migration(migrations.Migration):
    # dbextras.0003 drops the trigger that wrote `tsv` (ADR-0013). Removing
    # the column first would leave that trigger failing every chunk insert.
    dependencies = [
        ("kb", "0002_demo_kb_source"),
        ("dbextras", "0003_pg_search_bm25"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kbchunk",
            name="tsv",
        ),
    ]
